import { Module } from '../types';

export const tsFundamentals: Module = {
  id: 'ts-m1',
  title: 'Fundamentals',
  description: 'Variables, primitive types, and how TypeScript adds safety to JavaScript.',
  lessons: [
    {
      id: 'ts-l1',
      title: 'What TypeScript Is & Your First Types',
      summary: 'TypeScript = JavaScript + static types checked before your code runs.',
      estimatedMinutes: 10,
      concepts: ['ts-types', 'ts-variables'],
      content: [
        { kind: 'paragraph', text: 'TypeScript is a *superset* of JavaScript. Every valid JS program is valid TS, but TS adds a **type system** that catches mistakes before the code ever runs. At build time a compiler checks your types and then strips them away, producing plain JavaScript that runs anywhere JS runs — browsers, Node, phones.' },
        { kind: 'heading', text: 'Declaring typed variables' },
        { kind: 'paragraph', text: 'Use `let` for variables that change and `const` for ones that do not. You can annotate a type with a colon, but TypeScript usually *infers* it for you.' },
        { kind: 'code', language: 'typescript', code: 'let count: number = 0;\nconst name = "Ada";   // inferred as string\ncount = count + 1;     // ok\n// name = 42;          // Error: Type \'number\' is not assignable to type \'string\'', caption: 'Annotation is optional when the initial value makes the type obvious.' },
        { kind: 'callout', tone: 'tip', text: 'Prefer `const` by default. Reach for `let` only when you genuinely reassign the variable. This makes code easier to reason about.' },
        { kind: 'heading', text: 'The primitive types' },
        { kind: 'table', headers: ['Type', 'Example', 'Notes'], rows: [
          ['string', '"hello", `hi ${name}`', 'Text. Backticks allow interpolation.'],
          ['number', '42, 3.14, 0xff', 'One type for ints and floats.'],
          ['boolean', 'true, false', 'Logical values.'],
          ['null', 'null', 'Intentional absence.'],
          ['undefined', 'undefined', 'Not yet assigned.'],
        ] },
        { kind: 'heading', text: 'Why this matters' },
        { kind: 'paragraph', text: 'In plain JS, `"5" - 1` is `4` but `"5" + 1` is `"51"` — silent bugs. TypeScript flags type mismatches as you write, so you fix them in seconds instead of debugging in production.' },
        { kind: 'callout', tone: 'pitfall', title: 'Types vanish at runtime', text: 'Types are erased after compilation. You cannot check `if (x is number)` at runtime using a type — you use JavaScript checks like `typeof x === "number"`.' },
      ],
      exercises: [
        {
          id: 'ts-e1',
          title: 'Type a greeting',
          prompt: 'Declare a `const` named `userName` set to your name (a string) and a `const` `age` set to a number. Then `console.log` the sentence: `Hi, <userName>! You are <age>.`',
          language: 'typescript',
          starterCode: '// Declare userName and age, then log the greeting.\n',
          solution: 'const userName: string = "Ada";\nconst age: number = 30;\nconsole.log(`Hi, ${userName}! You are ${age}.`);',
          checks: [
            { type: 'regex', pattern: 'const\\s+userName', description: 'Declares a const userName' },
            { type: 'regex', pattern: 'const\\s+age', description: 'Declares a const age' },
            { type: 'runExpression', expression: 'typeof userName === "string" && typeof age === "number"', description: 'userName is a string and age is a number' },
            { type: 'runOutput', expected: 'Hi, Ada! You are 30.', description: 'Logs the greeting in the required format', trim: true },
          ],
          hints: [
            { text: 'Use template literals with backticks: `Hi, ${userName}!`' },
            { text: 'The expected output uses the name "Ada" and age 30 — match those exactly to pass the output check.' },
          ],
          concepts: ['ts-variables', 'ts-types'],
        },
      ],
      quiz: [
        {
          id: 'ts-q1',
          prompt: 'When are TypeScript types checked?',
          options: ['While the program is running', 'Before the program runs, at compile time', 'Only in the browser console', 'Never — they are just comments'],
          answerIndex: 1,
          explanation: 'Types are checked by the compiler before execution, then erased. They guide you while writing and disappear at runtime.',
          concepts: ['ts-types'],
        },
        {
          id: 'ts-q2',
          prompt: 'Which keyword should you prefer for a value you never reassign?',
          options: ['var', 'let', 'const', 'static'],
          answerIndex: 2,
          explanation: '`const` signals the binding never changes, making code easier to reason about. Use `let` only when you reassign.',
          concepts: ['ts-variables'],
        },
      ],
    },
    {
      id: 'ts-l2',
      title: 'Arrays, Tuples & Literal Types',
      summary: 'Typing collections of values and locking values to exact literals.',
      estimatedMinutes: 12,
      concepts: ['ts-arrays', 'ts-types'],
      content: [
        { kind: 'heading', text: 'Arrays' },
        { kind: 'paragraph', text: 'An array type is the element type followed by `[]`. All elements share that type.' },
        { kind: 'code', language: 'typescript', code: 'const scores: number[] = [90, 85, 100];\nconst names: string[] = ["Ada", "Linus"];\nscores.push(72);        // ok\n// scores.push("oops"); // Error: string not assignable to number' },
        { kind: 'paragraph', text: 'The alternative generic syntax `Array<number>` means the same thing. Prefer `number[]` for simple cases.' },
        { kind: 'heading', text: 'Tuples' },
        { kind: 'paragraph', text: 'A *tuple* is a fixed-length array where each position has its own type — great for returning a pair of related values.' },
        { kind: 'code', language: 'typescript', code: 'const point: [number, number] = [10, 20];\nconst entry: [string, number] = ["age", 30];\nconst [key, value] = entry; // key: string, value: number' },
        { kind: 'heading', text: 'Literal & union types' },
        { kind: 'paragraph', text: 'A *literal type* restricts a value to exact constants. Combine them with `|` (union) to model a fixed set of options — far safer than loose strings.' },
        { kind: 'code', language: 'typescript', code: 'type Direction = "north" | "south" | "east" | "west";\nlet heading: Direction = "north";\n// heading = "up"; // Error: not a valid Direction', caption: 'Unions of literals are how TypeScript models enums-by-string.' },
        { kind: 'callout', tone: 'tip', text: 'Literal unions give you autocomplete for every allowed value and catch typos like `"nort"` instantly.' },
      ],
      exercises: [
        {
          id: 'ts-e2',
          title: 'Average of scores',
          prompt: 'Given the array `scores`, compute the average and store it in a `const average`. Then log it. Do not hard-code the result — derive it from the array.',
          language: 'typescript',
          starterCode: 'const scores: number[] = [80, 90, 100];\n// Compute the average into `average` and log it.\n',
          solution: 'const scores: number[] = [80, 90, 100];\nconst total = scores.reduce((sum, s) => sum + s, 0);\nconst average = total / scores.length;\nconsole.log(average);',
          checks: [
            { type: 'notContains', value: '90)', description: 'Does not hard-code the answer' },
            { type: 'runExpression', expression: 'average === 90', description: 'average equals 90' },
            { type: 'regex', pattern: 'scores\\.(reduce|length)', description: 'Derives the value from the array' },
          ],
          hints: [
            { text: 'Sum with reduce: scores.reduce((sum, s) => sum + s, 0)' },
            { text: 'Divide the sum by scores.length to get the mean.' },
          ],
          concepts: ['ts-arrays'],
        },
        {
          id: 'ts-e3',
          title: 'Model a traffic light',
          prompt: 'Define a literal union type `Light` with the values "red", "yellow", "green". Write a function `next(light: Light): Light` that returns the next light in the cycle red→green→yellow→red. Log `next("red")`.',
          language: 'typescript',
          starterCode: '// Define the Light type and the next() function.\n',
          solution: 'type Light = "red" | "yellow" | "green";\nfunction next(light: Light): Light {\n  if (light === "red") return "green";\n  if (light === "green") return "yellow";\n  return "red";\n}\nconsole.log(next("red"));',
          checks: [
            { type: 'regex', pattern: 'type\\s+Light\\s*=', description: 'Defines a Light type alias' },
            { type: 'runExpression', expression: 'next("red") === "green" && next("green") === "yellow" && next("yellow") === "red"', description: 'Cycles red→green→yellow→red correctly' },
            { type: 'runOutput', expected: 'green', description: 'Logs the light after red', trim: true },
          ],
          hints: [
            { text: 'A union type: type Light = "red" | "yellow" | "green";' },
            { text: 'Handle each case with if statements returning the next color.' },
          ],
          concepts: ['ts-types', 'ts-functions'],
        },
      ],
      quiz: [
        {
          id: 'ts-q3',
          prompt: 'What does the type [string, number] describe?',
          options: ['An array of strings or numbers in any order', 'A fixed 2-element tuple: a string then a number', 'An object with string and number keys', 'A union of string and number'],
          answerIndex: 1,
          explanation: 'Square brackets with comma-separated types form a tuple — fixed length with a type per position.',
          concepts: ['ts-arrays'],
        },
        {
          id: 'ts-q4',
          prompt: 'Which type only allows the exact values "on" or "off"?',
          code: { language: 'typescript', code: 'type Switch = ???;' },
          options: ['string', '"on" & "off"', '"on" | "off"', 'boolean'],
          answerIndex: 2,
          explanation: 'A union of literal types `"on" | "off"` restricts the value to exactly those two strings.',
          concepts: ['ts-types'],
        },
      ],
    },
  ],
};
