import { Module } from '../types';

export const goBasics: Module = {
  id: 'go-m1',
  title: 'Getting Started',
  description: 'Packages, the main function, variables, basic types, printing, and constants.',
  lessons: [
    {
      id: 'go-l1',
      title: 'Packages, main & Printing',
      summary: 'Every Go program is a package; an executable starts at func main and prints with the fmt package.',
      estimatedMinutes: 12,
      concepts: ['go-packages', 'go-fmt'],
      content: [
        { kind: 'paragraph', text: 'Go is a compiled, statically-typed language designed for simplicity and fast builds. Unlike scripts, a Go program is organized into **packages**, and an executable program must declare `package main` and provide a `func main()` — the entry point the runtime calls when the program starts.' },
        { kind: 'heading', text: 'A minimal program' },
        { kind: 'code', language: 'go', code: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello, Go!")\n}', caption: 'Save as main.go and run with `go run main.go`.' },
        { kind: 'list', ordered: true, items: [
          '`package main` marks this file as part of an executable program (not a reusable library).',
          '`import "fmt"` pulls in the standard-library formatting package.',
          '`func main()` is where execution begins — no arguments, no return value.',
        ] },
        { kind: 'callout', tone: 'pitfall', title: 'Unused imports are errors', text: 'If you `import "fmt"` but never use it, Go refuses to compile: "imported and not used". Go treats unused imports and unused local variables as errors, not warnings — this keeps code clean but surprises newcomers.' },
        { kind: 'heading', text: 'Printing with fmt' },
        { kind: 'paragraph', text: 'The `fmt` package is your everyday tool for output. The three you will use constantly are `Println`, `Print`, and `Printf`.' },
        { kind: 'table', headers: ['Function', 'Behavior', 'Example'], rows: [
          ['fmt.Println', 'Prints args separated by spaces, then a newline', 'fmt.Println("a", 1) → "a 1\\n"'],
          ['fmt.Print', 'Prints args with no trailing newline', 'fmt.Print("a")'],
          ['fmt.Printf', 'Formats with verbs like %d, %s, %v', 'fmt.Printf("%s=%d\\n", k, v)'],
        ] },
        { kind: 'code', language: 'go', code: 'name := "Ada"\nage := 36\nfmt.Printf("%s is %d years old\\n", name, age)\nfmt.Printf("value: %v\\n", []int{1, 2, 3})', caption: '%s = string, %d = integer, %v = any value in its default format.' },
        { kind: 'callout', tone: 'tip', title: 'Println vs Printf', text: 'Use `Println` for quick debugging; use `Printf` when you need control over formatting. Remember `Printf` does NOT add a newline automatically — include `\\n` yourself.' },
      ],
      exercises: [
        {
          id: 'go-e1',
          title: 'Your first Go program',
          prompt: 'Write a complete Go program in package main that imports fmt and prints exactly "Hello, Gopher!" using fmt.Println.',
          language: 'go',
          starterCode: '// Write a complete program: package main, import fmt, func main that prints the greeting.\n',
          solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello, Gopher!")\n}',
          checks: [
            { type: 'contains', value: 'package main', description: 'Declares package main' },
            { type: 'contains', value: 'import "fmt"', description: 'Imports the fmt package' },
            { type: 'regex', pattern: 'func\\s+main\\s*\\(\\s*\\)', description: 'Defines func main()' },
            { type: 'contains', value: 'fmt.Println("Hello, Gopher!")', description: 'Prints the greeting with Println' },
          ],
          hints: [
            { text: 'An executable program always starts with `package main`.' },
            { text: 'The signature is exactly `func main() {` with no parameters and no return type.' },
          ],
          concepts: ['go-packages', 'go-fmt'],
          expectedOutput: 'Hello, Gopher!',
        },
        {
          id: 'go-e2',
          title: 'Format with Printf',
          prompt: 'Inside func main, use fmt.Printf with the verbs %s and %d to print the line "Ada scored 95" followed by a newline. Use the literal values "Ada" and 95 as arguments to Printf.',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// Use fmt.Printf with %s and %d here.\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Printf("%s scored %d\\n", "Ada", 95)\n}',
          checks: [
            { type: 'contains', value: 'fmt.Printf', description: 'Uses fmt.Printf' },
            { type: 'regex', pattern: '%s.*%d', description: 'Uses the %s and %d verbs in order' },
            { type: 'contains', value: '\\n', description: 'Includes an explicit newline' },
            { type: 'regex', pattern: '"Ada"', description: 'Passes the string "Ada"' },
          ],
          hints: [
            { text: 'Printf takes a format string first, then the values: fmt.Printf("%s ... %d\\n", a, b).' },
            { text: 'Printf does not add a newline, so end the format string with \\n.' },
          ],
          concepts: ['go-fmt'],
          expectedOutput: 'Ada scored 95',
        },
      ],
      quiz: [
        {
          id: 'go-q1',
          prompt: 'What does an executable Go program require at its entry point?',
          options: ['function start() in package app', 'package main with func main()', 'A class named Main', 'public static void main'],
          answerIndex: 1,
          explanation: 'Go runs an executable by calling func main() in the package named main. There are no classes and no static methods involved.',
          concepts: ['go-packages'],
        },
        {
          id: 'go-q2',
          prompt: 'Which statement about fmt.Printf is correct?',
          code: { language: 'go', code: 'fmt.Printf("%d items", 3)' },
          options: ['It automatically appends a newline', 'It prints "3 items" but no newline', 'It prints "%d items"', 'It is a compile error'],
          answerIndex: 1,
          explanation: 'Printf substitutes %d with 3 giving "3 items", but unlike Println it does NOT add a trailing newline — you must include \\n yourself.',
          concepts: ['go-fmt'],
        },
      ],
    },
    {
      id: 'go-l2',
      title: 'Variables, Types & Constants',
      summary: 'Declaring values with var and :=, Go basic types, zero values, and constants.',
      estimatedMinutes: 14,
      concepts: ['go-variables', 'go-types', 'go-constants'],
      content: [
        { kind: 'paragraph', text: 'Go gives you two ways to introduce a variable. The full `var` form works anywhere (including package scope), while the short `:=` form is the idiomatic choice inside functions.' },
        { kind: 'code', language: 'go', code: 'var count int = 0       // explicit type and value\nvar name = "Ada"        // type inferred as string\nvar active bool         // no value -> zero value (false)\n\nscore := 95             // short declaration, inferred int', caption: ':= can only be used inside a function, never at package level.' },
        { kind: 'callout', tone: 'pitfall', title: ':= versus =', text: 'Use `:=` to *declare and assign* a new variable. Use plain `=` to *reassign* an existing one. Writing `:=` for a variable that already exists in the same scope is a compile error ("no new variables on left side of :=").' },
        { kind: 'heading', text: 'Zero values' },
        { kind: 'paragraph', text: 'Go has no "uninitialized" memory. Every type has a **zero value** used when you declare without assigning. This makes programs predictable — there is no `undefined`.' },
        { kind: 'table', headers: ['Type', 'Zero value', 'Notes'], rows: [
          ['int, float64', '0', 'All numeric types default to 0.'],
          ['bool', 'false', 'Logical default.'],
          ['string', '"" (empty)', 'Not nil — an empty string.'],
          ['pointers, slices, maps', 'nil', 'Reference-like types default to nil.'],
        ] },
        { kind: 'heading', text: 'The basic types' },
        { kind: 'list', items: [
          '`int` / `int64` / `int32` — signed integers (`int` is platform-sized, usually 64-bit).',
          '`float64` / `float32` — floating-point numbers; `float64` is the default for decimals.',
          '`bool` — `true` or `false`.',
          '`string` — immutable UTF-8 text.',
        ] },
        { kind: 'callout', tone: 'warning', title: 'No implicit conversions', text: 'Go never mixes numeric types automatically. Adding an int to a float64 is an error — you must convert explicitly: `float64(myInt) + myFloat`.' },
        { kind: 'heading', text: 'Constants' },
        { kind: 'paragraph', text: 'A `const` is a value fixed at compile time. Constants can be grouped, and `iota` generates incrementing values — Go’s idiomatic way to define enums.' },
        { kind: 'code', language: 'go', code: 'const Pi = 3.14159\nconst greeting = "hello"\n\nconst (\n\tRed = iota   // 0\n\tGreen        // 1\n\tBlue         // 2\n)', caption: 'iota starts at 0 and increments for each line in the const block.' },
        { kind: 'callout', tone: 'info', title: 'Untyped constants', text: 'Constants like `const Pi = 3.14159` are *untyped* until used, so they flexibly fit int, float64, etc. This is why `const x = 10` can be added to a float64 without an explicit conversion.' },
      ],
      exercises: [
        {
          id: 'go-e3',
          title: 'Declare and print variables',
          prompt: 'In func main, use the short declaration := to create city set to "Oslo" and population set to 700000. Then print them with fmt.Println so the output is "Oslo 700000".',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// Declare city and population with :=, then print them.\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tcity := "Oslo"\n\tpopulation := 700000\n\tfmt.Println(city, population)\n}',
          checks: [
            { type: 'regex', pattern: 'city\\s*:=\\s*"Oslo"', description: 'Declares city with := and value "Oslo"' },
            { type: 'regex', pattern: 'population\\s*:=\\s*700000', description: 'Declares population with := and value 700000' },
            { type: 'contains', value: 'fmt.Println(city, population)', description: 'Prints both with Println' },
          ],
          hints: [
            { text: 'Short declaration form: name := value' },
            { text: 'fmt.Println separates its arguments with a single space.' },
          ],
          concepts: ['go-variables', 'go-fmt'],
          expectedOutput: 'Oslo 700000',
        },
        {
          id: 'go-e4',
          title: 'Constants and conversion',
          prompt: 'Define a const metersPerMile equal to 1609. In main, declare miles := 3 (an int) and compute meters as a float64: meters := float64(miles) * metersPerMile. Print meters with fmt.Println.',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\n// Define the constant here.\n\nfunc main() {\n\t// Declare miles, compute meters with an explicit conversion, then print.\n}',
          solution: 'package main\n\nimport "fmt"\n\nconst metersPerMile = 1609\n\nfunc main() {\n\tmiles := 3\n\tmeters := float64(miles) * metersPerMile\n\tfmt.Println(meters)\n}',
          checks: [
            { type: 'regex', pattern: 'const\\s+metersPerMile\\s*=\\s*1609', description: 'Defines the metersPerMile constant' },
            { type: 'contains', value: 'float64(miles)', description: 'Explicitly converts miles to float64' },
            { type: 'contains', value: 'fmt.Println(meters)', description: 'Prints the meters value' },
          ],
          hints: [
            { text: 'Go requires an explicit conversion to multiply an int by a float result: float64(miles).' },
            { text: 'The untyped constant metersPerMile adapts to the float64 context automatically.' },
          ],
          concepts: ['go-constants', 'go-types'],
          expectedOutput: '4827',
        },
      ],
      quiz: [
        {
          id: 'go-q3',
          prompt: 'What is the zero value of a string variable declared as `var s string`?',
          options: ['nil', 'undefined', 'An empty string ""', 'A runtime panic'],
          answerIndex: 2,
          explanation: 'Strings zero-value to "" (empty), not nil. Only reference-like types (pointers, slices, maps, channels, interfaces) zero-value to nil.',
          concepts: ['go-types', 'go-variables'],
        },
        {
          id: 'go-q4',
          prompt: 'Why does this line fail to compile?',
          code: { language: 'go', code: 'x := 5\nx := 6' },
          options: ['x is read-only', ':= cannot be used twice for the same variable in one scope', 'Integers are immutable', 'It compiles fine'],
          answerIndex: 1,
          explanation: ':= declares a NEW variable. The second line redeclares x, giving "no new variables on left side of :=". Use plain `x = 6` to reassign.',
          concepts: ['go-variables'],
        },
      ],
    },
  ],
};
