import { Module } from '../types';

export const goFunctions: Module = {
  id: 'go-m2',
  title: 'Functions, Control Flow & Errors',
  description: 'Functions, multiple return values, if/for/switch, the error convention, and defer.',
  lessons: [
    {
      id: 'go-l3',
      title: 'Functions & Control Flow',
      summary: 'Declaring functions, multiple return values, and Go’s if/for/switch.',
      estimatedMinutes: 15,
      concepts: ['go-functions', 'go-controlflow'],
      content: [
        { kind: 'paragraph', text: 'A Go function declares its parameter types after each name and its return type after the parameter list. There is one loop keyword (`for`) and a deliberately small set of control structures.' },
        { kind: 'code', language: 'go', code: 'func add(a int, b int) int {\n\treturn a + b\n}\n\n// Same parameter type can be grouped:\nfunc sub(a, b int) int {\n\treturn a - b\n}', caption: 'Types come after names; the return type comes after the parentheses.' },
        { kind: 'heading', text: 'Multiple return values' },
        { kind: 'paragraph', text: 'A distinctive Go feature: functions can return more than one value. This is used everywhere — most famously to return a result *and* an error together.' },
        { kind: 'code', language: 'go', code: 'func divmod(a, b int) (int, int) {\n\treturn a / b, a % b\n}\n\nq, r := divmod(17, 5) // q = 3, r = 2', caption: 'Callers receive both values with a single :=.' },
        { kind: 'callout', tone: 'tip', title: 'The blank identifier', text: 'Ignore a return value you do not need with the blank identifier `_`: `q, _ := divmod(17, 5)`. This avoids the "declared but not used" error.' },
        { kind: 'heading', text: 'if and for' },
        { kind: 'paragraph', text: 'Conditions are not wrapped in parentheses, but braces are always required. `if` can include a short statement before the condition — perfect for scoping an error check.' },
        { kind: 'code', language: 'go', code: 'if n := len(name); n > 3 {\n\tfmt.Println("long name")\n}\n\n// The only loop keyword is for:\nfor i := 0; i < 3; i++ {\n\tfmt.Println(i)\n}\n\n// for as a while loop:\nfor count < 10 {\n\tcount++\n}', caption: 'Variables declared in the if/for header are scoped to that block.' },
        { kind: 'heading', text: 'switch' },
        { kind: 'paragraph', text: 'Go’s `switch` does not fall through by default — no `break` needed. You can switch on a value or use a bare `switch` as a clean if/else chain.' },
        { kind: 'code', language: 'go', code: 'switch day {\ncase "Sat", "Sun":\n\tfmt.Println("weekend")\ndefault:\n\tfmt.Println("weekday")\n}\n\nswitch {\ncase score >= 90:\n\tgrade = "A"\ncase score >= 80:\n\tgrade = "B"\n}', caption: 'Each case can list multiple values; a bare switch evaluates boolean cases.' },
        { kind: 'callout', tone: 'warning', title: 'No automatic fallthrough', text: 'Unlike C or Java, Go cases break automatically. If you actually want to continue into the next case, use the explicit `fallthrough` keyword.' },
      ],
      exercises: [
        {
          id: 'go-e5',
          title: 'Min of two ints',
          prompt: 'Write a function min(a, b int) int that returns the smaller of two integers using an if statement. In main, print min(8, 3).',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\n// Define min(a, b int) int here.\n\nfunc main() {\n\t// Print min(8, 3)\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc min(a, b int) int {\n\tif a < b {\n\t\treturn a\n\t}\n\treturn b\n}\n\nfunc main() {\n\tfmt.Println(min(8, 3))\n}',
          checks: [
            { type: 'regex', pattern: 'func\\s+min\\s*\\(\\s*a\\s*,\\s*b\\s+int\\s*\\)\\s+int', description: 'Declares min(a, b int) int' },
            { type: 'contains', value: 'if a < b', description: 'Uses an if comparison' },
            { type: 'contains', value: 'fmt.Println(min(8, 3))', description: 'Prints min(8, 3)' },
          ],
          hints: [
            { text: 'Return a when a < b, otherwise return b.' },
            { text: 'Group same-typed params: func min(a, b int) int.' },
          ],
          concepts: ['go-functions', 'go-controlflow'],
          expectedOutput: '3',
        },
        {
          id: 'go-e6',
          title: 'Return two values',
          prompt: 'Write a function stats(nums []int) (int, int) that returns the sum and the count of the slice using a for-range loop. In main, call sum, count := stats([]int{2, 4, 6}) and print them with fmt.Println(sum, count).',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\n// Define stats(nums []int) (int, int) using a for loop.\n\nfunc main() {\n\t// Call stats and print sum and count.\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc stats(nums []int) (int, int) {\n\tsum := 0\n\tfor _, n := range nums {\n\t\tsum += n\n\t}\n\treturn sum, len(nums)\n}\n\nfunc main() {\n\tsum, count := stats([]int{2, 4, 6})\n\tfmt.Println(sum, count)\n}',
          checks: [
            { type: 'regex', pattern: 'func\\s+stats\\s*\\(\\s*nums\\s+\\[\\]int\\s*\\)\\s*\\(\\s*int\\s*,\\s*int\\s*\\)', description: 'Declares stats with two int return values' },
            { type: 'regex', pattern: 'for\\s+.*range\\s+nums', description: 'Iterates with for range over nums' },
            { type: 'regex', pattern: 'sum\\s*,\\s*count\\s*:=\\s*stats', description: 'Captures both return values' },
          ],
          hints: [
            { text: 'for _, n := range nums iterates over the values, ignoring the index with _.' },
            { text: 'len(nums) gives the count.' },
          ],
          concepts: ['go-functions', 'go-controlflow'],
          expectedOutput: '12 3',
        },
      ],
      quiz: [
        {
          id: 'go-q5',
          prompt: 'How many loop keywords does Go have?',
          options: ['Three: for, while, do', 'Two: for and while', 'One: for (which covers all cases)', 'Zero — recursion only'],
          answerIndex: 2,
          explanation: 'Go has exactly one loop keyword, `for`. It serves as a classic for loop, a while loop (for cond), and an infinite loop (for {}).',
          concepts: ['go-controlflow'],
        },
        {
          id: 'go-q6',
          prompt: 'What happens after a matching case in a Go switch (without fallthrough)?',
          options: ['It falls through to the next case', 'It breaks out of the switch automatically', 'It loops back to the top', 'It is a compile error without break'],
          answerIndex: 1,
          explanation: 'Go switch cases break automatically. You never write `break`; use the explicit `fallthrough` keyword if you want to continue into the next case.',
          concepts: ['go-controlflow'],
        },
      ],
    },
    {
      id: 'go-l4',
      title: 'Errors & defer',
      summary: 'Go’s explicit error return convention and cleanup with defer.',
      estimatedMinutes: 15,
      concepts: ['go-errors', 'go-defer'],
      content: [
        { kind: 'paragraph', text: 'Go has no exceptions for ordinary failures. Instead, functions that can fail return an `error` as their *last* return value. The caller checks it immediately. This makes the failure path visible in the code rather than hidden in a stack unwind.' },
        { kind: 'code', language: 'go', code: 'import (\n\t"errors"\n\t"fmt"\n)\n\nfunc divide(a, b int) (int, error) {\n\tif b == 0 {\n\t\treturn 0, errors.New("divide by zero")\n\t}\n\treturn a / b, nil\n}', caption: 'On success return a nil error; on failure return a zero result and a real error.' },
        { kind: 'heading', text: 'The if err != nil pattern' },
        { kind: 'paragraph', text: 'The canonical Go idiom checks the error right after the call. You will write this thousands of times.' },
        { kind: 'code', language: 'go', code: 'result, err := divide(10, 0)\nif err != nil {\n\tfmt.Println("error:", err)\n\treturn\n}\nfmt.Println("result:", result)', caption: 'Handle (or return) the error before using the result.' },
        { kind: 'callout', tone: 'tip', title: 'Wrapping errors', text: 'Add context as errors travel up the stack with fmt.Errorf and the %w verb: `fmt.Errorf("loading config: %w", err)`. Callers can still inspect the original with errors.Is / errors.As.' },
        { kind: 'callout', tone: 'pitfall', title: 'Do not ignore errors', text: 'Discarding an error with `result, _ := divide(...)` silences real failures. Only ignore an error when you are certain it cannot matter — and document why.' },
        { kind: 'heading', text: 'defer: cleanup that always runs' },
        { kind: 'paragraph', text: 'A `defer` schedules a call to run when the surrounding function returns — no matter how it returns. It is the idiomatic way to release resources (close files, unlock mutexes) right next to where you acquire them.' },
        { kind: 'code', language: 'go', code: 'func process() {\n\tfmt.Println("start")\n\tdefer fmt.Println("cleanup")\n\tfmt.Println("work")\n}\n// prints: start, work, cleanup', caption: 'Deferred calls run in LIFO order, after the rest of the function body.' },
        { kind: 'callout', tone: 'info', title: 'Arguments are evaluated immediately', text: 'A deferred call’s arguments are evaluated when the `defer` statement runs, but the call itself happens at return. This catches people off guard with loop variables.' },
      ],
      exercises: [
        {
          id: 'go-e7',
          title: 'Return an error',
          prompt: 'Write sqrtPositive(x float64) (float64, error) that returns an error created with errors.New("negative input") when x is negative, otherwise returns x (pretend it is the root) and nil. In main, call it with -1 and print the error if err != nil.',
          language: 'go',
          starterCode: 'package main\n\nimport (\n\t"errors"\n\t"fmt"\n)\n\n// Define sqrtPositive(x float64) (float64, error).\n\nfunc main() {\n\t// Call with -1.0 and handle the error.\n}',
          solution: 'package main\n\nimport (\n\t"errors"\n\t"fmt"\n)\n\nfunc sqrtPositive(x float64) (float64, error) {\n\tif x < 0 {\n\t\treturn 0, errors.New("negative input")\n\t}\n\treturn x, nil\n}\n\nfunc main() {\n\t_, err := sqrtPositive(-1.0)\n\tif err != nil {\n\t\tfmt.Println(err)\n\t}\n}',
          checks: [
            { type: 'regex', pattern: 'func\\s+sqrtPositive\\s*\\(\\s*x\\s+float64\\s*\\)\\s*\\(\\s*float64\\s*,\\s*error\\s*\\)', description: 'Returns (float64, error)' },
            { type: 'contains', value: 'errors.New("negative input")', description: 'Creates the error with errors.New' },
            { type: 'regex', pattern: 'if\\s+err\\s*!=\\s*nil', description: 'Checks the error with if err != nil' },
            { type: 'contains', value: 'return x, nil', description: 'Returns a nil error on success' },
          ],
          hints: [
            { text: 'On the failure path return a zero value and the error; on success return the value and nil.' },
            { text: 'Use the blank identifier to ignore the float result: _, err := sqrtPositive(-1.0).' },
          ],
          concepts: ['go-errors'],
          expectedOutput: 'negative input',
        },
        {
          id: 'go-e8',
          title: 'Cleanup with defer',
          prompt: 'In func main, print "open", then schedule "close" with defer, then print "use". Use fmt.Println for each. The defer must make "close" print last.',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// Print open, defer close, print use.\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("open")\n\tdefer fmt.Println("close")\n\tfmt.Println("use")\n}',
          checks: [
            { type: 'regex', pattern: 'defer\\s+fmt\\.Println\\("close"\\)', description: 'Defers the close print' },
            { type: 'contains', value: 'fmt.Println("open")', description: 'Prints open' },
            { type: 'contains', value: 'fmt.Println("use")', description: 'Prints use' },
            { type: 'notRegex', pattern: 'fmt\\.Println\\("use"\\)[\\s\\S]*defer', description: 'defer appears before the use print, not after' },
          ],
          hints: [
            { text: 'A deferred call runs when main returns, so it prints after "use".' },
            { text: 'Order in source: open, defer close, use.' },
          ],
          concepts: ['go-defer'],
          expectedOutput: 'open\nuse\nclose',
        },
      ],
      quiz: [
        {
          id: 'go-q7',
          prompt: 'How does idiomatic Go report an ordinary failure from a function?',
          options: ['It throws an exception', 'It returns an error as the last return value', 'It sets a global errno', 'It calls panic()'],
          answerIndex: 1,
          explanation: 'Go returns an error value (conventionally last). Callers check `if err != nil`. panic is reserved for truly unrecoverable situations, not normal failures.',
          concepts: ['go-errors'],
        },
        {
          id: 'go-q8',
          prompt: 'When does a deferred function call execute?',
          code: { language: 'go', code: 'func f() {\n\tdefer cleanup()\n\twork()\n}' },
          options: ['Immediately, before work()', 'When the enclosing function f returns', 'Only if work() panics', 'Never, unless called manually'],
          answerIndex: 1,
          explanation: 'defer schedules cleanup() to run when f returns — whether normally or via a panic — making it ideal for releasing resources.',
          concepts: ['go-defer'],
        },
      ],
    },
  ],
};
