import { Module } from '../types';

export const goCollections: Module = {
  id: 'go-m3',
  title: 'Slices, Maps & Structs',
  description: 'Arrays and slices, append, maps, structs, methods, and pointers.',
  lessons: [
    {
      id: 'go-l5',
      title: 'Slices & Maps',
      summary: 'Growable slices with append and keyed maps — Go’s core dynamic collections.',
      estimatedMinutes: 16,
      concepts: ['go-slices', 'go-maps'],
      content: [
        { kind: 'paragraph', text: 'An **array** in Go has a fixed length baked into its type (`[3]int`), so you rarely use them directly. The workhorse is the **slice** (`[]int`) — a flexible, growable view over an underlying array.' },
        { kind: 'code', language: 'go', code: 'var arr [3]int = [3]int{1, 2, 3} // fixed-length array\n\nnums := []int{10, 20, 30}        // slice literal\nfmt.Println(len(nums))           // 3\nfmt.Println(nums[0])             // 10\nfmt.Println(nums[1:3])           // [20 30] (slicing)', caption: 'Slice with low:high; the high index is exclusive.' },
        { kind: 'heading', text: 'Growing a slice with append' },
        { kind: 'paragraph', text: '`append` returns a (possibly new) slice with elements added. You must assign the result back — append does not mutate in place when it needs to grow.' },
        { kind: 'code', language: 'go', code: 'nums := []int{1, 2}\nnums = append(nums, 3)        // [1 2 3]\nnums = append(nums, 4, 5)     // [1 2 3 4 5]\n\nother := []int{6, 7}\nnums = append(nums, other...) // spread another slice', caption: 'Always reassign: nums = append(nums, ...).' },
        { kind: 'callout', tone: 'pitfall', title: 'Forgetting to reassign append', text: 'Calling `append(nums, 3)` without assigning the result loses the appended element. The compiler even flags it: "result of append is not used".' },
        { kind: 'heading', text: 'Maps: keyed collections' },
        { kind: 'paragraph', text: 'A map associates keys with values, like a dictionary. Create one with `make` (or a literal), and use the "comma ok" idiom to tell a missing key from a zero value.' },
        { kind: 'code', language: 'go', code: 'ages := make(map[string]int)\nages["Ada"] = 36\nages["Linus"] = 54\n\nage, ok := ages["Ada"] // age=36, ok=true\n_, exists := ages["X"]  // exists=false\n\ndelete(ages, "Linus")', caption: 'The second boolean ("ok") reports whether the key was present.' },
        { kind: 'callout', tone: 'warning', title: 'Assigning to a nil map panics', text: 'A map declared with `var m map[string]int` is nil; writing `m["a"]=1` panics at runtime. Always initialize with `make` or a literal before assigning.' },
        { kind: 'callout', tone: 'info', title: 'Map iteration order is random', text: 'Ranging over a map yields keys in an unspecified, randomized order. If you need stable output, collect the keys into a slice and sort them.' },
      ],
      exercises: [
        {
          id: 'go-e9',
          title: 'Build a slice with append',
          prompt: 'In main, start with squares := []int{} then append the squares 1, 4, 9 in a for loop over i from 1 to 3 (append i*i). Print squares with fmt.Println.',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tsquares := []int{}\n\t// Append i*i for i = 1..3, then print squares.\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tsquares := []int{}\n\tfor i := 1; i <= 3; i++ {\n\t\tsquares = append(squares, i*i)\n\t}\n\tfmt.Println(squares)\n}',
          checks: [
            { type: 'regex', pattern: 'squares\\s*=\\s*append\\(squares,', description: 'Reassigns the result of append' },
            { type: 'regex', pattern: 'for\\s+i\\s*:=\\s*1', description: 'Loops starting at i = 1' },
            { type: 'contains', value: 'i*i', description: 'Appends the square i*i' },
            { type: 'contains', value: 'fmt.Println(squares)', description: 'Prints the slice' },
          ],
          hints: [
            { text: 'append returns a new slice — assign it back: squares = append(squares, i*i).' },
            { text: 'Println formats a slice as [1 4 9].' },
          ],
          concepts: ['go-slices'],
          expectedOutput: '[1 4 9]',
        },
        {
          id: 'go-e10',
          title: 'Count with a map',
          prompt: 'In main, create counts := make(map[string]int). Range over the slice words := []string{"go", "go", "rust"} and increment counts[w] for each word. Then print counts["go"] with fmt.Println.',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\nfunc main() {\n\twords := []string{"go", "go", "rust"}\n\t// Build a map of word -> count and print counts["go"].\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\twords := []string{"go", "go", "rust"}\n\tcounts := make(map[string]int)\n\tfor _, w := range words {\n\t\tcounts[w]++\n\t}\n\tfmt.Println(counts["go"])\n}',
          checks: [
            { type: 'regex', pattern: 'make\\(map\\[string\\]int\\)', description: 'Creates the map with make' },
            { type: 'regex', pattern: 'for\\s+.*range\\s+words', description: 'Ranges over the words slice' },
            { type: 'regex', pattern: 'counts\\[w\\]\\+\\+', description: 'Increments the count for each word' },
            { type: 'contains', value: 'fmt.Println(counts["go"])', description: 'Prints the count for "go"' },
          ],
          hints: [
            { text: 'make a map first so writes do not panic on a nil map.' },
            { text: 'counts[w]++ works even when the key is new — it starts from the zero value 0.' },
          ],
          concepts: ['go-maps'],
          expectedOutput: '2',
        },
      ],
      quiz: [
        {
          id: 'go-q9',
          prompt: 'Why must you write `nums = append(nums, x)` rather than just `append(nums, x)`?',
          options: ['append is asynchronous', 'append may allocate a new underlying array and returns the new slice header', 'append mutates a copy by language rule', 'It is just a style preference'],
          answerIndex: 1,
          explanation: 'When a slice has no spare capacity, append allocates a new backing array and returns a new slice header. Ignoring the return value loses the appended data.',
          concepts: ['go-slices'],
        },
        {
          id: 'go-q10',
          prompt: 'What does the second value report in `v, ok := m["key"]`?',
          options: ['Whether the value is non-zero', 'Whether the key exists in the map', 'The length of the map', 'Whether the map is nil'],
          answerIndex: 1,
          explanation: 'The "comma ok" idiom returns the value and a boolean that is true only if the key was present — distinguishing a missing key from a stored zero value.',
          concepts: ['go-maps'],
        },
      ],
    },
    {
      id: 'go-l6',
      title: 'Structs, Methods & Pointers',
      summary: 'Custom types with structs, attaching methods, and modifying via pointer receivers.',
      estimatedMinutes: 16,
      concepts: ['go-structs', 'go-pointers'],
      content: [
        { kind: 'paragraph', text: 'A **struct** groups related fields into a single type — Go’s way to model records and domain objects. There are no classes; structs plus methods cover what other languages do with objects.' },
        { kind: 'code', language: 'go', code: 'type Point struct {\n\tX int\n\tY int\n}\n\np := Point{X: 1, Y: 2}    // named fields\nq := Point{3, 4}          // positional\nfmt.Println(p.X)          // 1\np.Y = 9                   // fields are mutable', caption: 'Field names starting uppercase are exported (visible to other packages).' },
        { kind: 'heading', text: 'Methods' },
        { kind: 'paragraph', text: 'A method is a function with a *receiver* — the value it is attached to, written before the method name. This is how you give behavior to a struct.' },
        { kind: 'code', language: 'go', code: 'func (p Point) DistanceFromOrigin() float64 {\n\treturn math.Sqrt(float64(p.X*p.X + p.Y*p.Y))\n}\n\nd := p.DistanceFromOrigin()', caption: 'A value receiver (p Point) operates on a copy of the struct.' },
        { kind: 'heading', text: 'Pointers & pointer receivers' },
        { kind: 'paragraph', text: 'A pointer holds the address of a value. To *modify* a struct from a method, use a **pointer receiver** (`*Point`); a value receiver only sees a copy and changes would be lost.' },
        { kind: 'code', language: 'go', code: 'func (p *Point) MoveBy(dx, dy int) {\n\tp.X += dx\n\tp.Y += dy\n}\n\np := Point{1, 1}\np.MoveBy(2, 3) // Go auto-takes &p; p is now {3, 4}', caption: 'Use a pointer receiver when the method mutates the struct or it is large.' },
        { kind: 'callout', tone: 'tip', title: 'When to use a pointer receiver', text: 'Use `*T` if the method modifies the receiver, or if copying the struct each call would be expensive. For consistency, if one method needs a pointer receiver, give all the type’s methods pointer receivers.' },
        { kind: 'callout', tone: 'pitfall', title: 'Value receiver mutation is silently lost', text: 'With a value receiver `func (p Point) MoveBy(...)`, assignments to p.X change only the local copy. The caller’s struct is unchanged — a common, confusing bug.' },
        { kind: 'callout', tone: 'info', title: 'No null-pointer surprises by default', text: 'The address-of operator is `&` and dereference is `*`. Go has no pointer arithmetic, so pointers are safe — but a nil pointer dereference still panics.' },
      ],
      exercises: [
        {
          id: 'go-e11',
          title: 'A struct with a method',
          prompt: 'Define a struct Rectangle with int fields Width and Height, and a value-receiver method Area() int returning Width*Height. In main, create r := Rectangle{Width: 3, Height: 4} and print r.Area().',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\n// Define Rectangle and its Area method.\n\nfunc main() {\n\t// Create a Rectangle and print its area.\n}',
          solution: 'package main\n\nimport "fmt"\n\ntype Rectangle struct {\n\tWidth  int\n\tHeight int\n}\n\nfunc (r Rectangle) Area() int {\n\treturn r.Width * r.Height\n}\n\nfunc main() {\n\tr := Rectangle{Width: 3, Height: 4}\n\tfmt.Println(r.Area())\n}',
          checks: [
            { type: 'regex', pattern: 'type\\s+Rectangle\\s+struct', description: 'Defines a Rectangle struct' },
            { type: 'regex', pattern: 'func\\s+\\(\\s*r\\s+Rectangle\\s*\\)\\s+Area\\s*\\(\\s*\\)\\s+int', description: 'Defines an Area() int method' },
            { type: 'contains', value: 'r.Width * r.Height', description: 'Computes width times height' },
            { type: 'contains', value: 'fmt.Println(r.Area())', description: 'Prints the area' },
          ],
          hints: [
            { text: 'A method’s receiver goes before the name: func (r Rectangle) Area() int.' },
            { text: 'Construct with named fields: Rectangle{Width: 3, Height: 4}.' },
          ],
          concepts: ['go-structs'],
          expectedOutput: '12',
        },
        {
          id: 'go-e12',
          title: 'Mutate via a pointer receiver',
          prompt: 'Give a Counter struct an int field N and a pointer-receiver method Inc() that does c.N++. In main, create c := Counter{}, call c.Inc() twice, then print c.N.',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\n// Define Counter with field N and a pointer-receiver Inc method.\n\nfunc main() {\n\t// Create a Counter, increment twice, print c.N.\n}',
          solution: 'package main\n\nimport "fmt"\n\ntype Counter struct {\n\tN int\n}\n\nfunc (c *Counter) Inc() {\n\tc.N++\n}\n\nfunc main() {\n\tc := Counter{}\n\tc.Inc()\n\tc.Inc()\n\tfmt.Println(c.N)\n}',
          checks: [
            { type: 'regex', pattern: 'func\\s+\\(\\s*c\\s+\\*Counter\\s*\\)\\s+Inc\\s*\\(\\s*\\)', description: 'Uses a pointer receiver *Counter' },
            { type: 'contains', value: 'c.N++', description: 'Increments the field' },
            { type: 'contains', value: 'fmt.Println(c.N)', description: 'Prints the final count' },
          ],
          hints: [
            { text: 'A pointer receiver is written *Counter so changes persist.' },
            { text: 'Go automatically takes the address of c when you call c.Inc().' },
          ],
          concepts: ['go-pointers', 'go-structs'],
          expectedOutput: '2',
        },
      ],
      quiz: [
        {
          id: 'go-q11',
          prompt: 'You want a method to permanently change a struct field. Which receiver do you use?',
          options: ['A value receiver (t T)', 'A pointer receiver (t *T)', 'Either works identically', 'Methods can never modify fields'],
          answerIndex: 1,
          explanation: 'A value receiver gets a copy, so mutations are lost. A pointer receiver (*T) operates on the original, so field changes persist.',
          concepts: ['go-pointers', 'go-structs'],
        },
        {
          id: 'go-q12',
          prompt: 'What makes a struct field visible to other packages?',
          code: { language: 'go', code: 'type User struct {\n\tName string\n\tage  int\n}' },
          options: ['A public keyword', 'Starting the field name with an uppercase letter', 'Tagging it with export', 'All fields are always visible'],
          answerIndex: 1,
          explanation: 'Go uses capitalization for visibility: Name is exported (uppercase), age is unexported (lowercase) and only visible within its own package.',
          concepts: ['go-structs'],
        },
      ],
    },
  ],
};
