import { Module } from '../types';

export const goConcurrency: Module = {
  id: 'go-m4',
  title: 'Interfaces & Concurrency',
  description: 'Interfaces and polymorphism, goroutines, channels, and sync.WaitGroup.',
  lessons: [
    {
      id: 'go-l7',
      title: 'Interfaces',
      summary: 'Defining behavior with interfaces and satisfying them implicitly.',
      estimatedMinutes: 15,
      concepts: ['go-interfaces'],
      content: [
        { kind: 'paragraph', text: 'An **interface** is a set of method signatures. Any type that has those methods satisfies the interface — *implicitly*. There is no `implements` keyword; if the methods match, it fits. This is Go’s lightweight take on polymorphism.' },
        { kind: 'code', language: 'go', code: 'type Shape interface {\n\tArea() float64\n}\n\ntype Circle struct{ R float64 }\nfunc (c Circle) Area() float64 { return 3.14159 * c.R * c.R }\n\ntype Square struct{ Side float64 }\nfunc (s Square) Area() float64 { return s.Side * s.Side }', caption: 'Circle and Square both satisfy Shape just by having an Area() float64 method.' },
        { kind: 'paragraph', text: 'Now any function can accept a Shape and work with all of them uniformly:' },
        { kind: 'code', language: 'go', code: 'func describe(s Shape) {\n\tfmt.Printf("area = %.2f\\n", s.Area())\n}\n\ndescribe(Circle{R: 2})  // area = 12.57\ndescribe(Square{Side: 3}) // area = 9.00', caption: 'One function, many concrete types — that is polymorphism in Go.' },
        { kind: 'callout', tone: 'tip', title: 'Keep interfaces small', text: 'Go’s most-used interfaces have a single method: `io.Reader`, `io.Writer`, `fmt.Stringer`. Small interfaces are easy to satisfy and compose. Define them where they are *used*, not where types are defined.' },
        { kind: 'heading', text: 'The empty interface & type assertions' },
        { kind: 'paragraph', text: '`interface{}` (or its alias `any`) is satisfied by every type — useful when you must hold a value of unknown type. Recover the concrete type with a type assertion or type switch.' },
        { kind: 'code', language: 'go', code: 'var x any = "hello"\ns, ok := x.(string) // s="hello", ok=true\n\nswitch v := x.(type) {\ncase string:\n\tfmt.Println("string:", v)\ncase int:\n\tfmt.Println("int:", v)\n}', caption: 'Use the comma-ok form of the assertion to avoid a panic on a wrong type.' },
        { kind: 'callout', tone: 'pitfall', title: 'A bare type assertion can panic', text: 'Writing `s := x.(string)` panics if x is not a string. Prefer the two-value form `s, ok := x.(string)` and check ok.' },
        { kind: 'callout', tone: 'info', title: 'Stringer for custom printing', text: 'Implement `String() string` (the fmt.Stringer interface) and fmt will use it automatically when printing your type with %v or Println.' },
      ],
      exercises: [
        {
          id: 'go-e13',
          title: 'Satisfy an interface',
          prompt: 'Define an interface Greeter with a method Greet() string. Define a struct English{} whose Greet() returns "Hello". In main, assign var g Greeter = English{} and print g.Greet().',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\n// Define the Greeter interface and an English type that satisfies it.\n\nfunc main() {\n\t// Use the interface to call Greet().\n}',
          solution: 'package main\n\nimport "fmt"\n\ntype Greeter interface {\n\tGreet() string\n}\n\ntype English struct{}\n\nfunc (e English) Greet() string {\n\treturn "Hello"\n}\n\nfunc main() {\n\tvar g Greeter = English{}\n\tfmt.Println(g.Greet())\n}',
          checks: [
            { type: 'regex', pattern: 'type\\s+Greeter\\s+interface', description: 'Declares the Greeter interface' },
            { type: 'regex', pattern: 'func\\s+\\(\\s*e\\s+English\\s*\\)\\s+Greet\\s*\\(\\s*\\)\\s+string', description: 'English implements Greet() string' },
            { type: 'regex', pattern: 'var\\s+g\\s+Greeter\\s*=\\s*English\\{\\}', description: 'Stores English in a Greeter variable' },
            { type: 'contains', value: 'g.Greet()', description: 'Calls Greet through the interface' },
          ],
          hints: [
            { text: 'No implements keyword is needed — matching the method signature is enough.' },
            { text: 'An empty struct is written English struct{} and constructed with English{}.' },
          ],
          concepts: ['go-interfaces'],
          expectedOutput: 'Hello',
        },
      ],
      quiz: [
        {
          id: 'go-q13',
          prompt: 'How does a Go type declare that it implements an interface?',
          options: ['With the implements keyword', 'By embedding the interface', 'Implicitly — by having all the interface’s methods', 'By registering it at startup'],
          answerIndex: 2,
          explanation: 'Go interfaces are satisfied implicitly (structural typing). If a type has the required methods, it satisfies the interface automatically — no declaration needed.',
          concepts: ['go-interfaces'],
        },
        {
          id: 'go-q14',
          prompt: 'Which form safely tests the concrete type behind an interface value?',
          options: ['s := x.(string)', 's, ok := x.(string)', 'typeof x', 'x instanceof string'],
          answerIndex: 1,
          explanation: 'The comma-ok type assertion `s, ok := x.(string)` returns false in ok instead of panicking when x is not a string.',
          concepts: ['go-interfaces'],
        },
      ],
    },
    {
      id: 'go-l8',
      title: 'Goroutines, Channels & WaitGroups',
      summary: 'Lightweight concurrency with goroutines and safe communication via channels.',
      estimatedMinutes: 18,
      concepts: ['go-goroutines', 'go-channels'],
      content: [
        { kind: 'paragraph', text: 'Concurrency is built into Go. A **goroutine** is an extremely lightweight thread of execution; you start one by prefixing a function call with the `go` keyword. The runtime multiplexes thousands of goroutines onto a few OS threads.' },
        { kind: 'code', language: 'go', code: 'go fmt.Println("runs concurrently")\n\ngo func() {\n\tfmt.Println("anonymous goroutine")\n}()', caption: 'go schedules the call to run independently; main does not wait for it.' },
        { kind: 'callout', tone: 'pitfall', title: 'main exits without waiting', text: 'When main returns, the program ends and any still-running goroutines are killed. You need synchronization (a channel or WaitGroup) to wait for them — a bare `go f()` may never print.' },
        { kind: 'heading', text: 'Channels: communicate, don’t share' },
        { kind: 'paragraph', text: 'Go’s motto is "Do not communicate by sharing memory; share memory by communicating." A **channel** is a typed conduit you send to with `ch <- v` and receive from with `v := <-ch`. An unbuffered channel blocks until both sides are ready, giving you synchronization for free.' },
        { kind: 'code', language: 'go', code: 'ch := make(chan int)\n\ngo func() {\n\tch <- 42 // send (blocks until received)\n}()\n\nv := <-ch    // receive\nfmt.Println(v) // 42', caption: 'The receive on the main goroutine waits for the send — they rendezvous.' },
        { kind: 'callout', tone: 'warning', title: 'Deadlocks', text: 'If every goroutine is blocked waiting on a channel that no one will ever satisfy, the runtime panics with "all goroutines are asleep - deadlock!". Make sure every send has a corresponding receive.' },
        { kind: 'heading', text: 'sync.WaitGroup: wait for many goroutines' },
        { kind: 'paragraph', text: 'When you fan out work to several goroutines and want to wait for all of them, a `sync.WaitGroup` is the standard tool: `Add` the count, `Done` as each finishes, and `Wait` for zero.' },
        { kind: 'code', language: 'go', code: 'var wg sync.WaitGroup\nfor i := 0; i < 3; i++ {\n\twg.Add(1)\n\tgo func(n int) {\n\t\tdefer wg.Done()\n\t\tfmt.Println("worker", n)\n\t}(i)\n}\nwg.Wait() // blocks until all three call Done', caption: 'Pass the loop variable as an argument so each goroutine gets its own copy.' },
        { kind: 'callout', tone: 'tip', title: 'defer wg.Done()', text: 'Call wg.Done() with defer at the top of the goroutine so it runs even if the work panics or returns early — guaranteeing the WaitGroup never hangs.' },
      ],
      exercises: [
        {
          id: 'go-e14',
          title: 'Send and receive on a channel',
          prompt: 'In main, make a channel ch := make(chan string). Start a goroutine with go func() that sends "done" into ch. Then receive into msg := <-ch and print msg.',
          language: 'go',
          starterCode: 'package main\n\nimport "fmt"\n\nfunc main() {\n\t// Make a channel, send "done" from a goroutine, receive and print it.\n}',
          solution: 'package main\n\nimport "fmt"\n\nfunc main() {\n\tch := make(chan string)\n\tgo func() {\n\t\tch <- "done"\n\t}()\n\tmsg := <-ch\n\tfmt.Println(msg)\n}',
          checks: [
            { type: 'regex', pattern: 'make\\(chan\\s+string\\)', description: 'Creates a string channel' },
            { type: 'regex', pattern: 'go\\s+func\\s*\\(\\s*\\)', description: 'Starts a goroutine' },
            { type: 'contains', value: 'ch <- "done"', description: 'Sends "done" on the channel' },
            { type: 'regex', pattern: 'msg\\s*:=\\s*<-ch', description: 'Receives from the channel' },
          ],
          hints: [
            { text: 'Send with ch <- value and receive with <-ch.' },
            { text: 'The receive blocks until the goroutine sends, so main waits correctly.' },
          ],
          concepts: ['go-goroutines', 'go-channels'],
          expectedOutput: 'done',
        },
        {
          id: 'go-e15',
          title: 'Wait for goroutines',
          prompt: 'Using sync, declare var wg sync.WaitGroup. In a loop i from 0 to 2, call wg.Add(1) and start a goroutine that uses defer wg.Done(). After the loop call wg.Wait() and then print "all done".',
          language: 'go',
          starterCode: 'package main\n\nimport (\n\t"fmt"\n\t"sync"\n)\n\nfunc main() {\n\tvar wg sync.WaitGroup\n\t// Launch 3 goroutines, wait for them, then print "all done".\n}',
          solution: 'package main\n\nimport (\n\t"fmt"\n\t"sync"\n)\n\nfunc main() {\n\tvar wg sync.WaitGroup\n\tfor i := 0; i < 3; i++ {\n\t\twg.Add(1)\n\t\tgo func() {\n\t\t\tdefer wg.Done()\n\t\t}()\n\t}\n\twg.Wait()\n\tfmt.Println("all done")\n}',
          checks: [
            { type: 'contains', value: 'var wg sync.WaitGroup', description: 'Declares a WaitGroup' },
            { type: 'contains', value: 'wg.Add(1)', description: 'Adds to the WaitGroup before each goroutine' },
            { type: 'contains', value: 'defer wg.Done()', description: 'Signals completion with defer wg.Done()' },
            { type: 'contains', value: 'wg.Wait()', description: 'Waits for all goroutines' },
            { type: 'contains', value: 'fmt.Println("all done")', description: 'Prints after waiting' },
          ],
          hints: [
            { text: 'Add(1) before launching each goroutine, Done() inside it, Wait() afterward.' },
            { text: 'defer wg.Done() guarantees the counter decrements even on early return.' },
          ],
          concepts: ['go-goroutines'],
          expectedOutput: 'all done',
        },
      ],
      quiz: [
        {
          id: 'go-q15',
          prompt: 'What happens to running goroutines when func main returns?',
          options: ['They keep running in the background', 'The program waits for all of them', 'They are terminated as the program exits', 'They restart automatically'],
          answerIndex: 2,
          explanation: 'When main returns the process exits, killing any remaining goroutines. Use a channel or WaitGroup to wait for goroutines you care about.',
          concepts: ['go-goroutines'],
        },
        {
          id: 'go-q16',
          prompt: 'What does receiving from an unbuffered channel do if no value is ready?',
          code: { language: 'go', code: 'v := <-ch' },
          options: ['Returns the zero value immediately', 'Blocks until a value is sent', 'Returns an error', 'Panics'],
          answerIndex: 1,
          explanation: 'An unbuffered channel receive blocks until another goroutine sends. This blocking is what synchronizes goroutines without explicit locks.',
          concepts: ['go-channels'],
        },
      ],
    },
  ],
};
